name: dev
on:
  push:
    branches:
      - 'dev'
      - 'main'
    tags-ignore:
      - 'v*'
      - 'preview_*'
      - 'test*'
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - 'docs/**'
      - 'fastlane/metadata/android/**'
      - 'tools/changelog-generator/**'
      - 'crowdin.yml'
      - 'fdroid.properties'
      - '*.json'
      - '**.md'
      - 'ReleaseNote*'
  workflow_dispatch:
    inputs:
      with_clean:
        description: "Run Gradle clean before building"
        type: boolean
        default: true
        required: false
  pull_request:
    branches:
      - 'dev'
      - 'main'
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '**.md'

jobs:
  build:
    # Matrix builds
    name: "Dev Ci"
    strategy:
      matrix:
        PRODUCT_VARIANT: [ModernCheckoutDebug, LegacyCheckoutDebug]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Sign Config
        env:
          SECRETS_KEY: ${{ secrets.KEY }}
          SECRETS_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          SECRETS_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SECRETS_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_FILE: ${{ github.workspace }}/key.jdk
          CONFIG_FILE: ${{ github.workspace }}/signing.properties
        run: |
          bash ${{ github.workspace }}/scripts/generate_signing_key.sh

      - name: Clean before building
        id: gradle-clean
        if: ${{ github.event.inputs.with_clean == 'true'}}
        run: |
          ./gradlew app:clean

      - name: Build with Gradle
        id: gradle-build
        run: |
          ./gradlew app:assemble${{ matrix.PRODUCT_VARIANT }} --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts_${{ matrix.PRODUCT_VARIANT }}
          path: ./app/build/outputs/apk/*/debug/*.apk
          retention-days: 3
