name: stable_release
on:
  push:
    tags:
      - "v**"
    paths-ignore:
      - '.github/**'

jobs:
  release:
    name: Create Stable Release Template
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Stable Release Template
        uses: softprops/action-gh-release@v1
        id: release_github
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.TOKEN }}
          name: "${{ github.ref_name }}"
          draft: true
          tag_name: ${{ github.ref }}
          body_path: ./GitHubReleaseNote.md
