name: stable_release
on:
  push:
    tags:
      - "v**"
    paths-ignore:
      - 'README.md'
      - 'ReleaseNote.md'
      - 'version.json'
      - '.github/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'

jobs:
  build:
    name: Create Stable Release Template
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Generate Release Note Template
        run: |
          echo "${{ github.ref_name }} " $(date +%Y.%m.%d) > ./ReleaseNoteTemplate.md
          echo "" >> ./ReleaseNoteTemplate.md
          echo "### ZH" >> ./ReleaseNoteTemplate.md
          echo "1." >> ./ReleaseNoteTemplate.md
          echo "" >> ./ReleaseNoteTemplate.md
          echo "### EN" >> ./ReleaseNoteTemplate.md
          echo "2." >> ./ReleaseNoteTemplate.md
          echo "" >> ./ReleaseNoteTemplate.md

      - name: Create Stable Release Template
        uses: softprops/action-gh-release@v1
        id: release_github
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.TOKEN }}
          name: "${{ github.ref_name }}"
          draft: true
          tag_name: ${{ github.ref }}
          body_path: ./ReleaseNoteTemplate.md
